### ISSUE TITLE
Auto download does not download videos

### ISSUE THREAD

**Issue by gerroon** [chibicitiberiu/ytsm#43]
Hi

I am not sure what the issue is, but it seems like Ytsm does not download any video. It shows them in thr Ui but they are not on the disk, even the channels are set to auto download.  

I am using on Debian X64 with Py3 virtualenv, just recloned the library

**Comment by gerroon** [comment]
Btw I am able to individually download them via the interface

**Comment by chibicitiberiu** [comment]
Can you obtain any logs? I'm thinking that some exception is thrown in one of the download task.

The logs are generally stored in the 'data' volume, next to the sqlite database.

**Comment by gerroon** [comment]
Well i have a huge log which over 370mb log. What am I looking for here? I can give you the log but it is not anonymized, so I prefer to provide only the relevant lines.


thanks

**Comment by gerroon** [comment]
I restarted the log

One of the lines I see is, not sure if it is relevant

```django.request|log.py|228|WARNING|Not Found: /media/thumbs/video/LWgVy5ZOB-w-best.jpe```

Well my media root is not /media/thumbs, it is ```MediaRoot=/media/DRIVE//YTSM_MEDIA```

**Comment by chibicitiberiu** [comment]
It is possible that, if you modified the media root path, some entries in the database still have the old path. If you see missing thumbnails, please open a separate issue, it's an unrelated problem.

Try to run a manual synchronization, and then check if there is anything that looks like an error. For exceptions, there is usually a trace which shows the exact file and line where the exception occurred.

**Comment by gerroon** [comment]
Ok but is "/media/thumbs/video" a relative path or an absolute path system wide?

**Comment by chibicitiberiu** [comment]
I checked, that is most likely a relative URL used in the web interface. The MediaRoot directory is mapped to the `http://host/media` URL.

There is a button in the lower right corner, as shown in this picture:
![screenshot_20181205_001749](https://user-images.githubusercontent.com/5184913/49476656-4336aa80-f823-11e8-93ee-4d609433bc43.png)

**Comment by chibicitiberiu** [comment]
Added an arrow to the picture:
![screenshot_20181205_001749](https://user-images.githubusercontent.com/5184913/49476810-a1638d80-f823-11e8-82b5-3b7793ed8611.png)

**Comment by gerroon** [comment]
I cant get some channels to download even after a total fresh install of ytsm.

Some of my channels download but some dont, even I set them to auto download.

For instance this one, it has 36 paegs (25 videos per page) and nothing has been downloaded.

https://www.youtube.com/user/Pavlovich2005/videos

**Comment by gerroon** [comment]
I actually already upgraded youtube-dl and Ytsm still not downloading my channels.

**Comment by chibicitiberiu** [comment]
There is an youtube-dl [issue](https://github.com/rg3/youtube-dl/issues/17457) about this exact problem. I'm not sure why it is happening, it was fixed a few months ago. What is the output of `pip show youtube-dl`?

**Comment by chibicitiberiu** [comment]
Alternatively, try to download one of the videos that is not working manually with youtube-dl, and see if the issue still occurs (as far as I can remember, the video ID appears in the logs). If that is the case, this is a problem on youtube-dl's end.

Since exceptions in the scheduler jobs are not properly handled, it is possible that an exception brings the entire scheduler down, which could explain why nothing is downloaded. There is already issue #14 for that, I will prioritize it.

**Comment by gerroon** [comment]
Well I have no problem downloading individual videos from a channel inside Ytsm.

**Comment by gerroon** [comment]
The downloaded video still is missing a thumbnail though.

**Comment by chibicitiberiu** [comment]
Do you still have this problem?

I noticed that in the logs, there is a message that says "9436 download candidates" and then "Global limit is set, can only download up to 0 videos. Limit is set, can only download up to 12 videos."

What this means is that you have set a global limit of 12 TOTAL videos (not videos per subscription). I think this might be the reason why it is not downloading anything. By downloading manually, this behavior is overridden, which is why you are able to download manually.
